# Generated by Django 5.1.1 on 2025-06-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('thoi_gian', models.DateTimeField()),
                ('dia_chi', models.CharField(max_length=255)),
                ('trang_thai', models.CharField(choices=[('chua_den', 'Chưa đến'), ('da_den', 'Đã đến'), ('da_huy', 'Đã hủy')], default='chua_den', max_length=10)),
            ],
        ),
    ]
