# Generated by Django 5.1.1 on 2025-06-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0002_datban'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chi_nhanh', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('gio_mo', models.TimeField()),
                ('gio_dong', models.TimeField()),
            ],
        ),
    ]
