# Generated by Django 5.1.1 on 2025-06-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0003_chinhanh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatBan',
        ),
    ]
