# Generated by Django 5.1.1 on 2025-06-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0004_delete_datban'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('thoi_gian', models.DateTimeField()),
                ('trang_thai', models.CharField(choices=[('chua_den', 'Chưa đến'), ('da_den', 'Đã đến'), ('da_huy', 'Đã hủy')], default='chua_den', max_length=10)),
                ('chi_nhanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterface.chinhanh')),
            ],
        ),
    ]
