# Generated by Django 5.1.1 on 2025-05-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiMonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiMon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenMonAn', models.CharField(max_length=100)),
                ('Anh', models.URLField(max_length=255)),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('TrangThai', models.BooleanField(default=True)),
                ('IdLoaiMonAn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loaimonan')),
            ],
        ),
    ]
