# Generated by Django 5.1.1 on 2025-05-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_loaimonan_monan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monan',
            name='Anh',
            field=models.CharField(max_length=255),
        ),
    ]
