# Generated by Django 5.1.1 on 2025-06-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_monan_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuBanAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenKhu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BanAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoBan', models.CharField(max_length=20)),
                ('TrangThai', models.BooleanField(default=True)),
                ('Khu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.khubanan')),
            ],
        ),
    ]
