# Generated by Django 5.1.1 on 2025-06-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_nhanvien'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NhanVien',
        ),
    ]
