# Generated by Django 5.1.1 on 2025-06-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('tai_khoan', models.CharField(max_length=100, unique=True)),
                ('mat_khau', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
