# Generated by Django 5.1.1 on 2025-06-08 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0005_datban'),
        ('account', '0008_nhanvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='chi_nhanh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserInterface.chinhanh'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='tinh_trang',
            field=models.CharField(choices=[('on', 'Đang làm'), ('off', 'Không làm'), ('on_leave', 'Đang nghỉ phép'), ('quit', 'Đã nghỉ làm')], default='off', max_length=10),
        ),
    ]
